### ISSUE TITLE
Careful

### ISSUE THREAD

**Issue by AbleLincoln** [JuliaW1/Colmar-Academy#4]
Be careful with how you use certain elements. Here you are using the`<footer>` element in the middle of the page. You should really only have one footer and it should be at the very bottom of the page. This is not an enforced rule, but in HTML sticking to these conventions will help make your webpage better for all users across all devices. 

https://github.com/JuliaW1/Colmar-Academy/blob/master/index.html#L58

**Comment by JuliaW1** [comment]
Thank you for your input.
