### ISSUE TITLE
Nice addition

### ISSUE THREAD

**Issue by AbleLincoln** [JuliaW1/Colmar-Academy#5]
These social links are a really great little feature. You're completely right that this is a must-have for any modern website. The one thing I would recommend is make these elements bigger and more prominent. Social media is a huge part of marketing, and marketing is all about getting people's attention! You might even want to consider putting these links in the header so people can find and click them easily.

https://github.com/JuliaW1/Colmar-Academy/blob/master/index.html#L178-L180

**Comment by JuliaW1** [comment]
Thank you for your input.
