### ISSUE TITLE
Awkward

### ISSUE THREAD

**Issue by AbleLincoln** [JuliaW1/Colmar-Academy#6]
These images for Section 2 look a bit awkward. Since you are applying both a width and a height to them, their aspect ratios are being stretched. You always want to try to maintain an images native aspect ratio as much as possible. In this case, since you needed a definite size to the images, I would recommend putting the image inside of a div and then adding the width/height to that div. That way the image will size itself to fit the div without messing with the aspect ratio.

https://github.com/JuliaW1/Colmar-Academy/blob/master/resources/css/style.css#L228-L230

**Comment by JuliaW1** [comment]
Thank you for your input.
